### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'code_snippet')

### ISSUE THREAD

**Issue by liujiacong** [spatie/ignition#62] opened 2022-03-02 15:54 UTC
**Please include some context and the contents of the console in your browser's developer tools.**

```
TypeError: Cannot read properties of undefined (reading 'code_snippet')
    at XE (http://laravel9.test/:72:249981)
    at mi (http://laravel9.test/:72:70706)
    at Ql (http://laravel9.test/:72:122308)
    at xc (http://laravel9.test/:72:109797)
    at _c (http://laravel9.test/:72:109725)
    at Cc (http://laravel9.test/:72:109588)
    at Nc (http://laravel9.test/:72:106582)
    at hc (http://laravel9.test/:72:103958)
    at nu (http://laravel9.test/:72:119816)
    at http://laravel9.test/:72:121187
```

## User Agent
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.62
```

**Comment by AdrianMrn** [comment] 2022-03-04 12:33
Thanks for reporting this issue! We've managed to reproduce it and will soon release a fix.

Since multiple issues were posted for this bug, I'll go ahead and close this one and post further updates in #59

**Closed by AdrianMrn** 2022-03-04 12:33 UTC

**Comment by AlexVanderbist** [comment] 2022-03-04 13:02
Thanks for your help!

The issue has since been resolved in https://github.com/spatie/ignition-ui/commit/dbfc5255e8add6919e5b25ec061e89b133d86b79. A new version of spatie/ignition has been tagged and running `composer update` in your project will automatically pull this in.
