### ISSUE TITLE
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by sanadhiflaoui** [spatie/ignition#116] opened 2022-03-30 14:38 UTC
**Please include some context and the contents of the console in your browser's developer tools.**

## JavaScript Error
```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Rl (http://localhost:8000/api/quiz/:148:100946)
    at Cc (http://localhost:8000/api/quiz/:148:112448)
    at t.unstable_runWithPriority (http://localhost:8000/api/quiz/:148:11072)
    at $a (http://localhost:8000/api/quiz/:148:56140)
    at Lc (http://localhost:8000/api/quiz/:148:110483)
    at Ec (http://localhost:8000/api/quiz/:148:106602)
    at http://localhost:8000/api/quiz/:148:56362
    at t.unstable_runWithPriority (http://localhost:8000/api/quiz/:148:11072)
    at $a (http://localhost:8000/api/quiz/:148:56140)
    at qa (http://localhost:8000/api/quiz/:148:56308)
```

## Reproduction Steps
Please tell us what you were doing when this error occurred, so we can more easily debug it and find a solution.

1. …

## User Agent
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
```

**Comment by AlexVanderbist** [comment] 2022-04-01 10:11
Duplicate of #109

**Closed by AlexVanderbist** 2022-04-01 10:11 UTC
