### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'code_snippet')

### ISSUE THREAD

**Issue by inclick24** [spatie/ignition#65] opened 2022-03-02 17:50 UTC
```TypeError: Cannot read properties of undefined (reading 'code_snippet')    at zE (http://localhost/dynamic_filter/public/:72:257091)    at mi (http://localhost/dynamic_filter/public/:72:70706)    at Ql (http://localhost/dynamic_filter/public/:72:122308)    at xc (http://localhost/dynamic_filter/public/:72:109797)    at _c (http://localhost/dynamic_filter/public/:72:109725)    at Cc (http://localhost/dynamic_filter/public/:72:109588)    at Nc (http://localhost/dynamic_filter/public/:72:106582)    at hc (http://localhost/dynamic_filter/public/:72:103958)    at nu (http://localhost/dynamic_filter/public/:72:119816)    at http://localhost/dynamic_filter/public/:72:121187```

**Comment by AdrianMrn** [comment] 2022-03-04 12:33
Thanks for reporting this issue! We've managed to reproduce it and will soon release a fix.

Since multiple issues were posted for this bug, I'll go ahead and close this one and post further updates in #59

**Closed by AdrianMrn** 2022-03-04 12:33 UTC
