### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'n.code_snippet')

### ISSUE THREAD

**Issue by gkedar** [spatie/ignition#63] opened 2022-03-02 17:00 UTC
**Please include some context and the contents of the console in your browser's developer tools.**

```
XE@http://localhost/:74:249980
mi@http://localhost/:74:70707
Ql@http://localhost/:74:122310
xc@http://localhost/:74:109799
_c@http://localhost/:74:109727
Cc@http://localhost/:74:109590
Nc@http://localhost/:74:106584
hc@http://localhost/:74:103960
nu@http://localhost/:74:119818
@http://localhost/:74:121189
Oc@http://localhost/:74:106961
cu@http://localhost/:74:121175
render@http://localhost/:74:128585
@http://localhost/:74:496823
global code@http://localhost/:78:18
```

## User Agent
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15
```

**Comment by AdrianMrn** [comment] 2022-03-04 12:33
Thanks for reporting this issue! We've managed to reproduce it and will soon release a fix.

Since multiple issues were posted for this bug, I'll go ahead and close this one and post further updates in #59

**Closed by AdrianMrn** 2022-03-04 12:33 UTC

**Comment by AlexVanderbist** [comment] 2022-03-04 13:02
Thanks for your help!

The issue has since been resolved in https://github.com/spatie/ignition-ui/commit/dbfc5255e8add6919e5b25ec061e89b133d86b79. A new version of spatie/ignition has been tagged and running `composer update` in your project will automatically pull this in.
