### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'code_snippet')

### ISSUE THREAD

**Issue by acgtwentyone** [spatie/ignition#72] opened 2022-03-03 11:36 UTC
**Something went wrong in Ignition!**

**An error occurred in Ignition's UI. Please open an issue on [the Ignition GitHub repo] and make sure to include any errors or warnings in the developer console.**

![Screenshot 2022-03-03 at 10 36 08](https://user-images.githubusercontent.com/94224806/156557292-3bf76fe9-5273-47be-b81d-68d3f173cb5d.png)

```
TypeError: Cannot read properties of undefined (reading 'code_snippet')
    at XE (http://192.168.0.159:8001/login:52:249981)
    at mi (http://192.168.0.159:8001/login:52:70706)
    at Ql (http://192.168.0.159:8001/login:52:122308)
    at xc (http://192.168.0.159:8001/login:52:109797)
    at _c (http://192.168.0.159:8001/login:52:109725)
    at Cc (http://192.168.0.159:8001/login:52:109588)
    at Nc (http://192.168.0.159:8001/login:52:106582)
    at hc (http://192.168.0.159:8001/login:52:103958)
    at nu (http://192.168.0.159:8001/login:52:119816)
    at http://192.168.0.159:8001/login:52:121187
```

## User Agent
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36
```

**Comment by acgtwentyone** [comment] 2022-03-03 11:38
After migrate laravel to 9 from 8. This is the error i am getting.

**Comment by AdrianMrn** [comment] 2022-03-04 12:34
Thanks for reporting this issue! We've managed to reproduce it and will soon release a fix.

Since multiple issues were posted for this bug, I'll go ahead and close this one and post further updates in #59

**Closed by AdrianMrn** 2022-03-04 12:34 UTC

**Comment by AlexVanderbist** [comment] 2022-03-04 13:02
Thanks for your help!

The issue has since been resolved in https://github.com/spatie/ignition-ui/commit/dbfc5255e8add6919e5b25ec061e89b133d86b79. A new version of spatie/ignition has been tagged and running `composer update` in your project will automatically pull this in.

**Comment by acgtwentyone** [comment] 2022-03-05 21:23
Ok. Actually this issues occured because after upgraded to laravel 9, google-drive package i had installed was not working anymore.
