### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'n.code_snippet')

### ISSUE THREAD

**Issue by hamert-gharibi** [spatie/ignition#68] opened 2022-03-02 23:35 UTC
**Please include some context and the contents of the console in your browser's developer tools.**

```
XE@http://localhost/laravel-crud/public/:72:249980
mi@http://localhost/laravel-crud/public/:72:70707
Ql@http://localhost/laravel-crud/public/:72:122310
xc@http://localhost/laravel-crud/public/:72:109799
_c@http://localhost/laravel-crud/public/:72:109727
Cc@http://localhost/laravel-crud/public/:72:109590
Nc@http://localhost/laravel-crud/public/:72:106584
hc@http://localhost/laravel-crud/public/:72:103960
nu@http://localhost/laravel-crud/public/:72:119818
@http://localhost/laravel-crud/public/:72:121189
Oc@http://localhost/laravel-crud/public/:72:106961
cu@http://localhost/laravel-crud/public/:72:121175
render@http://localhost/laravel-crud/public/:72:128585
@http://localhost/laravel-crud/public/:72:496823
global code@http://localhost/laravel-crud/public/:76:18
```

## User Agent
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15
```

**Comment by AdrianMrn** [comment] 2022-03-04 12:34
Thanks for reporting this issue! We've managed to reproduce it and will soon release a fix.

Since multiple issues were posted for this bug, I'll go ahead and close this one and post further updates in #59

**Closed by AdrianMrn** 2022-03-04 12:34 UTC
