### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'code_snippet')

### ISSUE THREAD

**Issue by polnunezr** [spatie/ignition#113] opened 2022-03-29 10:05 UTC
**Please include some context and the contents of the console in your browser's developer tools.**

```
TypeError: Cannot read properties of undefined (reading 'code_snippet')
    at XE (http://localhost/ABP_BROGGI/public/carta:72:249981)
    at mi (http://localhost/ABP_BROGGI/public/carta:72:70706)
    at Ql (http://localhost/ABP_BROGGI/public/carta:72:122308)
    at xc (http://localhost/ABP_BROGGI/public/carta:72:109797)
    at _c (http://localhost/ABP_BROGGI/public/carta:72:109725)
    at Cc (http://localhost/ABP_BROGGI/public/carta:72:109588)
    at Nc (http://localhost/ABP_BROGGI/public/carta:72:106582)
    at hc (http://localhost/ABP_BROGGI/public/carta:72:103958)
    at nu (http://localhost/ABP_BROGGI/public/carta:72:119816)
    at http://localhost/ABP_BROGGI/public/carta:72:121187
```

## User Agent
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
```

**Comment by AlexVanderbist** [comment] 2022-04-01 10:10
Duplicate of #109

**Closed by AlexVanderbist** 2022-04-01 10:10 UTC
