### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'slice')

### ISSUE THREAD

**Issue by wahyusnjy** [spatie/ignition#157] opened 2022-08-19 07:19 UTC
**Please include some context and the contents of the console in your browser's developer tools.**

## JavaScript Error
```
TypeError: Cannot read properties of undefined (reading 'slice')
    at parseKey (http://localhost:8000/menu-pengajuan-pembelian/update/1:171:45034)
    at e.value (http://localhost:8000/menu-pengajuan-pembelian/update/1:171:45661)
    at e.value (http://localhost:8000/menu-pengajuan-pembelian/update/1:171:44927)
    at e.value (http://localhost:8000/menu-pengajuan-pembelian/update/1:171:44749)
    at e.value (http://localhost:8000/menu-pengajuan-pembelian/update/1:171:43733)
    at e.value (http://localhost:8000/menu-pengajuan-pembelian/update/1:171:43379)
    at m.value (http://localhost:8000/menu-pengajuan-pembelian/update/1:171:33335)
    at t.format (http://localhost:8000/menu-pengajuan-pembelian/update/1:171:105466)
    at Ic (http://localhost:8000/menu-pengajuan-pembelian/update/1:171:108148)
    at Ef (http://localhost:8000/menu-pengajuan-pembelian/update/1:166:186645)
```

## Reproduction Steps
Please tell us what you were doing when this error occurred, so we can more easily debug it and find a solution.

1. …

## User Agent
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
```

**Comment by AlexVanderbist** [comment] 2022-08-26 09:43
Thanks! This seems to be a duplicate of another issue on this repo. I'll close this issue for now and we'll continue this discussion there.

**Closed by AlexVanderbist** 2022-08-26 09:43 UTC
