### ISSUE TITLE
TypeError: n is undefined

### ISSUE THREAD

**Issue by mdsabbirweb** [spatie/ignition#74] opened 2022-03-03 18:32 UTC
**Please include some context and the contents of the console in your browser's developer tools.**

```
XE@http://localhost/shorturl/:72:249965
mi@http://localhost/shorturl/:72:70706
Ql@http://localhost/shorturl/:72:122308
xc@http://localhost/shorturl/:72:109799
_c@http://localhost/shorturl/:72:109727
Cc@http://localhost/shorturl/:72:109588
Nc@http://localhost/shorturl/:72:106582
hc@http://localhost/shorturl/:72:103958
nu@http://localhost/shorturl/:72:119816
cu/<@http://localhost/shorturl/:72:121189
Oc@http://localhost/shorturl/:72:106960
cu@http://localhost/shorturl/:72:121175
render@http://localhost/shorturl/:72:128583
window.ignite@http://localhost/shorturl/:72:496817
@http://localhost/shorturl/:76:12

```

## User Agent
```
Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0
```

**Comment by AdrianMrn** [comment] 2022-03-04 12:34
Thanks for reporting this issue! We've managed to reproduce it and will soon release a fix.

Since multiple issues were posted for this bug, I'll go ahead and close this one and post further updates in #59

**Closed by AdrianMrn** 2022-03-04 12:34 UTC

**Comment by AlexVanderbist** [comment] 2022-03-04 13:02
Thanks for your help!

The issue has since been resolved in https://github.com/spatie/ignition-ui/commit/dbfc5255e8add6919e5b25ec061e89b133d86b79. A new version of spatie/ignition has been tagged and running `composer update` in your project will automatically pull this in.
