### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'code_snippet')

### ISSUE THREAD

**Issue by Coder0010** [spatie/ignition#119] opened 2022-04-04 20:30 UTC
**Please include some context and the contents of the console in your browser's developer tools.**

```
TypeError: Cannot read properties of undefined (reading 'code_snippet')
    at XE (http://localhost:8001/:72:249981)
    at mi (http://localhost:8001/:72:70706)
    at Ql (http://localhost:8001/:72:122308)
    at xc (http://localhost:8001/:72:109797)
    at _c (http://localhost:8001/:72:109725)
    at Cc (http://localhost:8001/:72:109588)
    at Nc (http://localhost:8001/:72:106582)
    at hc (http://localhost:8001/:72:103958)
    at nu (http://localhost:8001/:72:119816)
    at http://localhost:8001/:72:121187
```

## User Agent
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36
```

**Comment by AlexVanderbist** [comment] 2022-04-24 12:12
Thanks! This seems to be a duplicate of #109. I'll close this issue for now and we'll continue this discussion there.

**Closed by AlexVanderbist** 2022-04-24 12:12 UTC
