### ISSUE TITLE
TypeError: n is undefined

### ISSUE THREAD

**Issue by Atm14** [spatie/ignition#58] opened 2022-03-02 00:22 UTC
```zE@http://127.0.0.1:8000/:72:257075mi@http://127.0.0.1:8000/:72:70706Ql@http://127.0.0.1:8000/:72:122308xc@http://127.0.0.1:8000/:72:109799_c@http://127.0.0.1:8000/:72:109727Cc@http://127.0.0.1:8000/:72:109588Nc@http://127.0.0.1:8000/:72:106582hc@http://127.0.0.1:8000/:72:103958nu@http://127.0.0.1:8000/:72:119816cu/<@http://127.0.0.1:8000/:72:121189Oc@http://127.0.0.1:8000/:72:106960cu@http://127.0.0.1:8000/:72:121175render@http://127.0.0.1:8000/:72:128583window.ignite@http://127.0.0.1:8000/:72:508564@http://127.0.0.1:8000/:76:12```

**Comment by AlexVanderbist** [comment] 2022-03-02 10:05
Hi, thanks for letting is know. This looks like a duplicate of #59. We'll continue the issue there!

**Closed by AlexVanderbist** 2022-03-02 10:05 UTC
