### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'code_snippet')

### ISSUE THREAD

**Issue by fasilkp1** [spatie/ignition#122] opened 2022-04-07 12:26 UTC
**Please include some context and the contents of the console in your browser's developer tools.**

```
TypeError: Cannot read properties of undefined (reading 'code_snippet')
    at XE (http://65.0.250.19/demo/public/:72:249981)
    at mi (http://65.0.250.19/demo/public/:72:70706)
    at Ql (http://65.0.250.19/demo/public/:72:122308)
    at xc (http://65.0.250.19/demo/public/:72:109797)
    at _c (http://65.0.250.19/demo/public/:72:109725)
    at Cc (http://65.0.250.19/demo/public/:72:109588)
    at Nc (http://65.0.250.19/demo/public/:72:106582)
    at hc (http://65.0.250.19/demo/public/:72:103958)
    at nu (http://65.0.250.19/demo/public/:72:119816)
    at http://65.0.250.19/demo/public/:72:121187
```

## User Agent
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36
```

**Comment by AlexVanderbist** [comment] 2022-04-24 12:20
Thanks! This seems to be a duplicate of #109. I'll close this issue for now and we'll continue this discussion there.

**Closed by AlexVanderbist** 2022-04-24 12:20 UTC
