### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'code_snippet')

### ISSUE THREAD

**Issue by rajwebhost** [spatie/ignition#64] opened 2022-03-02 17:49 UTC
```TypeError: Cannot read properties of undefined (reading 'code_snippet')    at zE (http://laravelraj.net/:72:257091)    at mi (http://laravelraj.net/:72:70706)    at Ql (http://laravelraj.net/:72:122308)    at xc (http://laravelraj.net/:72:109797)    at _c (http://laravelraj.net/:72:109725)    at Cc (http://laravelraj.net/:72:109588)    at Nc (http://laravelraj.net/:72:106582)    at hc (http://laravelraj.net/:72:103958)    at nu (http://laravelraj.net/:72:119816)    at http://laravelraj.net/:72:121187```

**Comment by AdrianMrn** [comment] 2022-03-04 12:33
Thanks for reporting this issue! We've managed to reproduce it and will soon release a fix.

Since multiple issues were posted for this bug, I'll go ahead and close this one and post further updates in #59

**Closed by AdrianMrn** 2022-03-04 12:33 UTC

**Comment by AlexVanderbist** [comment] 2022-03-04 13:02
Thanks for your help!

The issue has since been resolved in https://github.com/spatie/ignition-ui/commit/dbfc5255e8add6919e5b25ec061e89b133d86b79. A new version of spatie/ignition has been tagged and running `composer update` in your project will automatically pull this in.
