### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'code_snippet')

### ISSUE THREAD

**Issue by netdjw** [spatie/ignition#145] opened 2022-06-29 14:45 UTC
**Please include some context and the contents of the console in your browser's developer tools.**

```
TypeError: Cannot read properties of undefined (reading 'code_snippet')
    at XE (http://mydomain.test/:74:249981)
    at mi (http://mydomain.test/:74:70706)
    at Ql (http://mydomain.test/:74:122308)
    at xc (http://mydomain.test/:74:109797)
    at _c (http://mydomain.test/:74:109725)
    at Cc (http://mydomain.test/:74:109588)
    at Nc (http://mydomain.test/:74:106582)
    at hc (http://mydomain.test/:74:103958)
    at nu (http://mydomain.test/:74:119816)
    at http://mydomain.test/:74:121187
```

## User Agent
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
```

**Comment by AlexVanderbist** [comment] 2022-08-26 09:42
Thanks! This seems to be a duplicate of another issue on this repo. I'll close this issue for now and we'll continue this discussion there.

**Closed by AlexVanderbist** 2022-08-26 09:42 UTC
