### ISSUE TITLE
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by NatLunar** [spatie/ignition#143] opened 2022-06-17 01:50 UTC
**Please include some context and the contents of the console in your browser's developer tools.**

## JavaScript Error
```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at yl (http://127.0.0.1:8000/:146:141704)
    at Xp (http://127.0.0.1:8000/:146:251719)
    at Kp (http://127.0.0.1:8000/:146:252080)
    at gh (http://127.0.0.1:8000/:146:267692)
    at HTMLUnknownElement.v (http://127.0.0.1:8000/:146:103631)
    at Object.Bn (http://127.0.0.1:8000/:146:103956)
    at qn (http://127.0.0.1:8000/:146:104917)
    at mh (http://127.0.0.1:8000/:146:265326)
    at t.unstable_runWithPriority (http://127.0.0.1:8000/:146:38304)
    at Ws (http://127.0.0.1:8000/:146:148134)
```

## Reproduction Steps
Please tell us what you were doing when this error occurred, so we can more easily debug it and find a solution.

1. …

## User Agent
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
```

**Comment by AlexVanderbist** [comment] 2022-08-26 09:42
Thanks! This seems to be a duplicate of another issue on this repo. I'll close this issue for now and we'll continue this discussion there.

**Closed by AlexVanderbist** 2022-08-26 09:42 UTC
