### ISSUE TITLE
TypeError: n is undefined

### ISSUE THREAD

**Issue by loay317** [spatie/ignition#55] opened 2022-03-01 21:11 UTC
```zE@http://212.106.73.53/:72:257075mi@http://212.106.73.53/:72:70706Ql@http://212.106.73.53/:72:122308xc@http://212.106.73.53/:72:109799_c@http://212.106.73.53/:72:109727Cc@http://212.106.73.53/:72:109588Nc@http://212.106.73.53/:72:106582hc@http://212.106.73.53/:72:103958nu@http://212.106.73.53/:72:119816cu/<@http://212.106.73.53/:72:121189Oc@http://212.106.73.53/:72:106960cu@http://212.106.73.53/:72:121175render@http://212.106.73.53/:72:128583window.ignite@http://212.106.73.53/:72:508564@http://212.106.73.53/:76:12```

**Comment by AlexVanderbist** [comment] 2022-03-02 10:04
Hi, thanks for letting is know. This looks like a duplicate of #59. We'll continue the issue there!

**Closed by AlexVanderbist** 2022-03-02 10:04 UTC
