### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'slice')

### ISSUE THREAD

**Issue by adityadees** [spatie/ignition#142] opened 2022-06-05 08:15 UTC
**Please include some context and the contents of the console in your browser's developer tools.**

## JavaScript Error
```
TypeError: Cannot read properties of undefined (reading 'slice')
    at parseKey (http://127.0.0.1:8000/blog/:173:45034)
    at e.value (http://127.0.0.1:8000/blog/:173:45661)
    at e.value (http://127.0.0.1:8000/blog/:173:44927)
    at e.value (http://127.0.0.1:8000/blog/:173:44749)
    at e.value (http://127.0.0.1:8000/blog/:173:43733)
    at e.value (http://127.0.0.1:8000/blog/:173:43379)
    at m.value (http://127.0.0.1:8000/blog/:173:33335)
    at t.format (http://127.0.0.1:8000/blog/:173:105466)
    at Ic (http://127.0.0.1:8000/blog/:173:108148)
    at Ef (http://127.0.0.1:8000/blog/:168:186645)
```

## Reproduction Steps
Please tell us what you were doing when this error occurred, so we can more easily debug it and find a solution.

1. …

## User Agent
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
```

**Comment by AlexVanderbist** [comment] 2022-08-26 09:42
Thanks! This seems to be a duplicate of another issue on this repo. I'll close this issue for now and we'll continue this discussion there.

**Closed by AlexVanderbist** 2022-08-26 09:42 UTC
