### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'code_snippet')

### ISSUE THREAD

**Issue by dds813** [spatie/ignition#82] opened 2022-03-04 09:01 UTC
**Please include some context and the contents of the console in your browser's developer tools.**

```
TypeError: Cannot read properties of undefined (reading 'code_snippet')
    at XE (https://gxxc.dds138.com/:72:249981)
    at mi (https://gxxc.dds138.com/:72:70706)
    at Ql (https://gxxc.dds138.com/:72:122308)
    at xc (https://gxxc.dds138.com/:72:109797)
    at _c (https://gxxc.dds138.com/:72:109725)
    at Cc (https://gxxc.dds138.com/:72:109588)
    at Nc (https://gxxc.dds138.com/:72:106582)
    at hc (https://gxxc.dds138.com/:72:103958)
    at nu (https://gxxc.dds138.com/:72:119816)
    at https://gxxc.dds138.com/:72:121187
```

## User Agent
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.109 Safari/537.36
```

**Comment by AdrianMrn** [comment] 2022-03-04 12:34
Thanks for reporting this issue! We've managed to reproduce it and will soon release a fix.

Since multiple issues were posted for this bug, I'll go ahead and close this one and post further updates in #59

**Closed by AdrianMrn** 2022-03-04 12:34 UTC
