### ISSUE TITLE
Error: Minified React error 

### ISSUE THREAD

**Issue by azerioid** [spatie/ignition#102] opened 2022-03-18 08:39 UTC
Something went wrong in Ignition!
An error occurred in Ignition's UI. Please open an issue on [the Ignition GitHub repo](https://github.com/spatie/ignition/issues/new?title=Error:%20Minified%20React%20error%20#130;%20visit%20https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=symbol&args[]=%20for%20the%20full%20message%20or%20use%20the%20non-minified%20dev%20environment%20for%20full%20errors%20and%20additional%20helpful%20warnings.&labels=bug&body=%0A**Please%20include%20some%20context%20and%20the%20contents%20of%20the%20console%20in%20your%20browser's%20developer%20tools.**%0A%0A%23%23%20JavaScript%20Error%0A%60%60%60%0AError%3A%20Minified%20React%20error%20%23130%3B%20visit%20https%3A%2F%2Freactjs.org%2Fdocs%2Ferror-decoder.html%3Finvariant%3D130%26args%5B%5D%3Dsymbol%26args%5B%5D%3D%20for%20the%20full%20message%20or%20use%20the%20non-minified%20dev%20environment%20for%20full%20errors%20and%20additional%20helpful%20warnings.%0A%20%20%20%20at%20Vc%20(http%3A%2F%2Flocalhost%3A3000%2Flogin%3A172%3A118007)%0A%20%20%20%20at%20c%20(http%3A%2F%2Flocalhost%3A3000%2Flogin%3A172%3A63539)%0A%20%20%20%20at%20p%20(http%3A%2F%2Flocalhost%3A3000%2Flogin%3A172%3A64516)%0A%20%20%20%20at%20E%20(http%3A%2F%2Flocalhost%3A3000%2Flogin%3A172%3A65158)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A3000%2Flogin%3A172%3A67432%0A%20%20%20%20at%20Fi%20(http%3A%2F%2Flocalhost%3A3000%2Flogin%3A172%3A78440)%0A%20%20%20%20at%20Yl%20(http%3A%2F%2Flocalhost%3A3000%2Flogin%3A172%3A123981)%0A%20%20%20%20at%20Ac%20(http%3A%2F%2Flocalhost%3A3000%2Flogin%3A172%3A109591)%0A%20%20%20%20at%20Rc%20(http%3A%2F%2Flocalhost%3A3000%2Flogin%3A172%3A109519)%0A%20%20%20%20at%20Oc%20(http%3A%2F%2Flocalhost%3A3000%2Flogin%3A172%3A109382)%0A%60%60%60%0A%0A%23%23%20Reproduction%20Steps%0APlease%20tell%20us%20what%20you%20were%20doing%20when%20this%20error%20occurred%2C%20so%20we%20can%20more%20easily%20debug%20it%20and%20find%20a%20solution.%0A%0A1.%20%E2%80%A6%0A%0A%23%23%20User%20Agent%0A%60%60%60%0AMozilla%2F5.0%20(Macintosh%3B%20Intel%20Mac%20OS%20X%2010_15_7)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F99.0.4844.74%20Safari%2F537.36%0A%60%60%60%0A) and make sure to include any errors or warnings in the developer console.

**Comment by AlexVanderbist** [comment] 2022-03-19 13:09
Duplicate of #101

**Closed by AlexVanderbist** 2022-03-19 13:09 UTC
