### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'code_snippet')

### ISSUE THREAD

**Issue by VictordaSilvaf** [spatie/ignition#73] opened 2022-03-03 16:58 UTC
**Please include some context and the contents of the console in your browser's developer tools.**

```
TypeError: Cannot read properties of undefined (reading 'code_snippet')
    at XE (http://159.223.172.169/:72:249981)
    at mi (http://159.223.172.169/:72:70706)
    at Ql (http://159.223.172.169/:72:122308)
    at xc (http://159.223.172.169/:72:109797)
    at _c (http://159.223.172.169/:72:109725)
    at Cc (http://159.223.172.169/:72:109588)
    at Nc (http://159.223.172.169/:72:106582)
    at hc (http://159.223.172.169/:72:103958)
    at nu (http://159.223.172.169/:72:119816)
    at http://159.223.172.169/:72:121187
```

## User Agent
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
```

**Comment by AdrianMrn** [comment] 2022-03-04 12:34
Thanks for reporting this issue! We've managed to reproduce it and will soon release a fix.

Since multiple issues were posted for this bug, I'll go ahead and close this one and post further updates in #59

**Closed by AdrianMrn** 2022-03-04 12:34 UTC

**Comment by AlexVanderbist** [comment] 2022-03-04 13:02
Thanks for your help!

The issue has since been resolved in https://github.com/spatie/ignition-ui/commit/dbfc5255e8add6919e5b25ec061e89b133d86b79. A new version of spatie/ignition has been tagged and running `composer update` in your project will automatically pull this in.
