### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'code_snippet')

### ISSUE THREAD

**Issue by Bharath56080** [spatie/ignition#146] opened 2022-06-30 04:27 UTC
**Please include some context and the contents of the console in your browser's developer tools.**

```
TypeError: Cannot read properties of undefined (reading 'code_snippet')
    at XE (https://attendance1.shivila.in/loginCheck:72:249981)
    at mi (https://attendance1.shivila.in/loginCheck:72:70706)
    at Ql (https://attendance1.shivila.in/loginCheck:72:122308)
    at xc (https://attendance1.shivila.in/loginCheck:72:109797)
    at _c (https://attendance1.shivila.in/loginCheck:72:109725)
    at Cc (https://attendance1.shivila.in/loginCheck:72:109588)
    at Nc (https://attendance1.shivila.in/loginCheck:72:106582)
    at hc (https://attendance1.shivila.in/loginCheck:72:103958)
    at nu (https://attendance1.shivila.in/loginCheck:72:119816)
    at https://attendance1.shivila.in/loginCheck:72:121187
```

## User Agent
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36 Edg/103.0.1264.37
```

**Comment by AlexVanderbist** [comment] 2022-08-26 09:42
Thanks! This seems to be a duplicate of another issue on this repo. I'll close this issue for now and we'll continue this discussion there.

**Closed by AlexVanderbist** 2022-08-26 09:42 UTC
