### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'code_snippet')

### ISSUE THREAD

**Issue by developersharif** [spatie/ignition#88] opened 2022-03-05 04:29 UTC
**Please include some context and the contents of the console in your browser's developer tools.**

```
TypeError: Cannot read properties of undefined (reading 'code_snippet')
    at XE (http://localhost/php/laravel/laraApp/public/:72:249981)
    at mi (http://localhost/php/laravel/laraApp/public/:72:70706)
    at Ql (http://localhost/php/laravel/laraApp/public/:72:122308)
    at xc (http://localhost/php/laravel/laraApp/public/:72:109797)
    at _c (http://localhost/php/laravel/laraApp/public/:72:109725)
    at Cc (http://localhost/php/laravel/laraApp/public/:72:109588)
    at Nc (http://localhost/php/laravel/laraApp/public/:72:106582)
    at hc (http://localhost/php/laravel/laraApp/public/:72:103958)
    at nu (http://localhost/php/laravel/laraApp/public/:72:119816)
    at http://localhost/php/laravel/laraApp/public/:72:121187
```

## User Agent
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
```

**Comment by ankurk91** [comment] 2022-03-05 05:57
Duplicate of https://github.com/spatie/ignition/issues/59

**Comment by AdrianMrn** [comment] 2022-03-07 12:06
This issue should have been resolved in the latest version of the package. Could you confirm you're on that version and otherwise upgrade, please?

**Closed by AdrianMrn** 2022-03-07 12:06 UTC
